# Generated by Django 4.2.16 on 2025-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='log_level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10),
        ),
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.CharField(default='System', max_length=50),
        ),
    ]
