# Generated by Django 4.2.16 on 2025-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_feedback_rating_supportticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
