# Generated by Django 4.2.16 on 2025-04-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0006_alter_faq_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
