# Generated by Django 4.2.16 on 2025-03-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('grant_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='calls_app.grantcall')),
            ],
        ),
        migrations.CreateModel(
            name='GrantChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='calls_app.grantquestion')),
            ],
        ),
    ]
