# Generated by Django 4.2.16 on 2025-03-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0002_grantquestion_grantchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantquestion',
            name='question_type',
            field=models.CharField(choices=[('open', 'Open-Ended'), ('multiple_choice', 'Multiple Choice')], default='open', max_length=20),
        ),
    ]
