# Generated by Django 4.2.16 on 2025-03-20 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls_app', '0003_grantquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantcall',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_grants', to=settings.AUTH_USER_MODEL),
        ),
    ]
