# Generated by Django 4.2.16 on 2025-04-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0005_grantresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantresponse',
            name='grant_call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='calls_app.grantcall'),
        ),
        migrations.AddField(
            model_name='grantresponse',
            name='is_final_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grantresponse',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
