# Generated by Django 4.2.16 on 2025-04-02 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0006_grantresponse_grant_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantresponse',
            name='grant_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='calls_app.grantcall'),
        ),
    ]
