# Generated by Django 4.2.16 on 2025-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0007_alter_grantresponse_grant_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='grant_responses/'),
        ),
    ]
