# Generated by Django 4.2.16 on 2025-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0008_grantresponse_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantquestion',
            name='choices_text',
            field=models.TextField(blank=True, help_text='Enter one choice per line (only for multiple-choice questions).', null=True),
        ),
        migrations.AlterField(
            model_name='grantquestion',
            name='question_type',
            field=models.CharField(choices=[('open', 'Open-Ended'), ('multiple_choice', 'Multiple Choice'), ('file_upload', 'File Upload')], default='open', max_length=20),
        ),
    ]
