# Generated by Django 4.2.16 on 2025-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_app', '0009_grantquestion_choices_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantquestion',
            name='choices_text',
        ),
        migrations.AlterField(
            model_name='grantquestion',
            name='question_type',
            field=models.CharField(choices=[('open', 'Open-Ended'), ('file_upload', 'File Upload')], default='open', max_length=20),
        ),
        migrations.DeleteModel(
            name='GrantChoice',
        ),
    ]
